### ISSUE TITLE
GoDaddy updated it's login (again)

### ISSUE THREAD

**Issue by trkadi** [observerss/pygodaddy#15]
Hi!

Same problem as the previous issue. Sorry for making a new ticket, but it's clean now :+1: :).

**Comment by archerne** [comment]
I am getting this error in my logs:
`2015-09-01 13:54:22,263 Login routine broken, godaddy may have updated their log
in mechanism                                                                    
Traceback (most recent call last):                                              
  File "/usr/local/lib/python2.7/site-packages/pygodaddy/client.py", line 101, i
n login                                                                         
    viewstate = re.compile(r'id="__VIEWSTATE" value="([^"]+)"').search(r.text).g
roup(1)                                                                         
AttributeError: 'NoneType' object has no attribute 'group'`

**Comment by trkadi** [comment]
Yeah this is also what I got. The worst thing is that I did not find any information about this godaddy api.. Previously when this error happened I localized the code snipplet in the python code but couldn't correct it cause of the lack of any documentation..

**Comment by dawg6** [comment]
There is a fix posted for this in the other open issue (https://github.com/observerss/pygodaddy/issues/12). Scroll down to the comment posted by @BryceGough. 

Perhaps this issue should be closed as a duplicate?

**Comment by trkadi** [comment]
Yeah I modified my ipdater script too and also posted into issue #12.
